import datetime
import os
from pathlib import Path

from ..config import settings
from ..exceptions import FileProcessingException
from ..config.logging_config import get_logger

logger = get_logger(__name__)


class DraftStore:
    """Service responsible for persisting email drafts.

    Draft files are written to the ``Pending_Approval`` directory defined in
    ``settings.PENDING_APPROVAL_PATH``. Filenames are based on a timestamp and the
    email subject to make them easy to locate.
    """

    def __init__(self, pending_dir: str | Path = None):
        self.pending_dir = Path(pending_dir) if pending_dir else Path(settings.PENDING_APPROVAL_PATH)
        self.pending_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"DraftStore initialized with directory: {self.pending_dir}")

    def _sanitize_filename(self, text: str) -> str:
        """Sanitize a string for safe filesystem usage.

        Removes or replaces characters that are unsafe for file names.
        """
        # Simple sanitisation: replace spaces with underscores and drop path separators
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in text)
        return safe

    def save_draft(self, subject: str, to_addr: str, body: str, platform: str = "email", thread_id: str = None, message_id: str = None) -> Path:
        """Write a draft markdown file and return its path.

        The file format is::

            Subject: <subject>
            To: <to_addr>
            Platform: <platform>
            Thread-ID: <thread_id> (Optional)
            Message-ID: <message_id> (Optional)

            <body>

        Parameters
        ----------
        subject: str
            Email subject line.
        to_addr: str
            Recipient email address.
        body: str
            The email content generated by the AI.
        platform: str
            Platform name (email, linkedin, etc.)
        thread_id: str
            Gmail Thread ID for threading.
        message_id: str
            Gmail Message ID for threading.

        Returns
        -------
        Path
            Absolute path to the created draft file.
        """
        timestamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
        safe_subject = self._sanitize_filename(subject)[:50]
        filename = f"{timestamp}_{safe_subject}.md"
        draft_path = self.pending_dir / filename
        try:
            with draft_path.open("w", encoding="utf-8") as f:
                f.write(f"Subject: {subject}\n")
                f.write(f"Platform: {platform}\n")
                if thread_id:
                    f.write(f"Thread-ID: {thread_id}\n")
                if message_id:
                    f.write(f"Message-ID: {message_id}\n")
                f.write(f"To: {to_addr}\n\n")
                f.write(body)
            logger.info(f"Draft saved to {draft_path}")
            return draft_path
        except Exception as e:
            raise FileProcessingException(f"Failed to write draft file {draft_path}: {e}")
