import logging
from pathlib import Path

from ..config import settings
from ..services.file_mover import FileMover
from ..utils.security import is_safe_path

logger = logging.getLogger(__name__)


class LinkedInPoster:
    """Posts LinkedIn drafts generated by :class:`LinkedInProcessor`.

    As with :class:`EmailSender`, this class operates in mock mode when no
    LinkedIn credentials are provided. The draft is moved to the DONE folder
    after a successful (or mock) post.
    """

    def __init__(self):
        # In a real implementation you would retrieve LinkedIn OAuth tokens here.
        self.api_key = getattr(settings, "LINKEDIN_API_KEY", "")
        if self.api_key:
            logger.info("LinkedInPoster configured with real API key")
        else:
            logger.warning("No LinkedIn API key – operating in mock mode")

    def post_draft(self, draft_path: Path) -> bool:
        """Post the LinkedIn draft.

        Parameters
        ----------
        draft_path: Path
            Absolute path to a markdown draft stored in ``settings.PENDING_APPROVAL_PATH``.

        Returns
        -------
        bool
            ``True`` on success (or mock success), ``False`` on failure.
        """
        try:
            base_dir = Path(settings.APPROVED_PATH)
            if not is_safe_path(draft_path, base_dir):
                logger.error("Unsafe draft path detected: %s", draft_path)
                return False

            content = draft_path.read_text(encoding="utf-8")
            logger.debug("LinkedIn draft content (first 200 chars): %s", content[:200])

            if self.api_key:
                # Real LinkedIn API call would be placed here.
                logger.info("Posting to LinkedIn via real API (mocked in this repo)")
            else:
                logger.info("Mock LinkedIn post – no API key configured")

            return True
        except Exception as e:
            logger.error("Failed to post LinkedIn draft %s: %s", draft_path, e)
            return False
